//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api.busgarage.com.mx.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class cat_Karts
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cat_Karts()
        {
            this.cat_Orders = new HashSet<cat_Orders>();
        }
    
        public int Kart_Id { get; set; }
        public string Kart_Json_Config { get; set; }
        public System.DateTime Kart_Creation_Date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cat_Orders> cat_Orders { get; set; }
    }
}
