//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api.busgarage.com.mx.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CMS_BusgarageEntities : DbContext
    {
        public CMS_BusgarageEntities()
            : base("name=CMS_BusgarageEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cat_Karts> cat_Karts { get; set; }
        public virtual DbSet<cat_Categories> cat_Categories { get; set; }
        public virtual DbSet<cat_Reviews> cat_Reviews { get; set; }
        public virtual DbSet<cat_About_Us_Sections> cat_About_Us_Sections { get; set; }
        public virtual DbSet<cat_Offers_Image> cat_Offers_Image { get; set; }
        public virtual DbSet<cat_Slider_Images> cat_Slider_Images { get; set; }
        public virtual DbSet<cat_Admin_Login> cat_Admin_Login { get; set; }
        public virtual DbSet<cat_Products> cat_Products { get; set; }
        public virtual DbSet<vw_Products> vw_Products { get; set; }
        public virtual DbSet<cat_Product_Galery_Images> cat_Product_Galery_Images { get; set; }
        public virtual DbSet<vw_Sepomex_Info> vw_Sepomex_Info { get; set; }
        public virtual DbSet<cat_Sepomex> cat_Sepomex { get; set; }
        public virtual DbSet<cat_Orders> cat_Orders { get; set; }
        public virtual DbSet<vw_Orders> vw_Orders { get; set; }
    }
}
